import {useEffect, useState} from 'react';
import {JobPost, listJobPosts, updateJobPost} from './api';
import TutorRecommendations from './TutorRecommendations';
export default function JobManagement() {
  const [selectedJob, setSelectedJob] = useState<JobPost | null>(null);
  const [onlyEmpty, setOnlyEmpty] = useState(false);
  const [success, setSuccess] = useState('');
  const [jobs, setJobs] = useState<JobPost[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setJobs(await listJobPosts()); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const change = async (job: JobPost) => { setSaving(job.id); try { await updateJobPost(job.id, job.status === 'OPEN' ? 'CLOSED' : 'OPEN'); await load(); } catch (e: any) { setError(e.message); } finally { setSaving(''); } };
  return <>{selectedJob && <TutorRecommendations job={selectedJob} onClose={() => setSelectedJob(null)} onSaved={() => {setSelectedJob(null); setSuccess("Đã gửi đề xuất để phụ huynh duyệt."); void load();}} />}{success && <p role="status">{success}</p>}<label><input type="checkbox" checked={onlyEmpty} onChange={e => setOnlyEmpty(e.target.checked)} /> Chỉ bài đang mở chưa có ứng tuyển</label>{error && <div className="error-banner">{error}<button onClick={load}>Thử lại</button></div>}<section className="table-wrap"><table><thead><tr><th>Môn / trình độ</th><th>Mục tiêu / địa điểm</th><th>Lịch học</th><th>Trạng thái</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={5}>Đang tải...</td></tr> : jobs.filter(job => !onlyEmpty || (job.status === 'OPEN' && job.applicantCount === 0)).length === 0 ? <tr><td colSpan={5}>Chưa có bài đăng.</td></tr> : jobs.filter(job => !onlyEmpty || (job.status === 'OPEN' && job.applicantCount === 0)).map(job => <tr key={job.id}><td data-label="Môn / trình độ">{job.subject} · {job.grade}<small>{Number(job.budget).toLocaleString('vi-VN')} đ / buổi</small></td><td data-label="Mục tiêu / địa điểm">{job.goal}<small>{job.location}</small></td><td data-label="Lịch học">{job.schedule?.map((slot, i) => <small key={i}>{slot.dayOfWeek}: {slot.startTime} – {slot.endTime}</small>)}</td><td data-label="Trạng thái">{{OPEN: 'Đang mở', CLOSED: 'Đã đóng', MATCHED: 'Đã chọn gia sư'}[job.status]}<small>{job.applicantCount} ứng tuyển · {job.recommendationCount} đề xuất</small></td><td data-label="Thao tác">{job.status === 'OPEN' && job.applicantCount === 0 && <button className="view-button" disabled={!!saving} onClick={() => {setSelectedJob(job); setSuccess('');}}>Đề xuất gia sư</button>}{job.status !== 'MATCHED' && <button disabled={!!saving} onClick={() => change(job)}>{saving === job.id ? 'Đang lưu...' : job.status === 'OPEN' ? 'Đóng bài đăng' : 'Mở bài đăng'}</button>}</td></tr>)}</tbody></table></section></>;
}
